version: 1
validation: sovereign
default_denom: utat
genesis:
  chain_id: tat-1
build:
  binary: tatcoind

accounts:
  - name: validator
    coins:
      - 100000000utat

  - name: foundation
    coins:
      - 100000000utat

  - name: ecosystem
    coins:
      - 100000000utat

  - name: community
    coins:
      - 100000000utat

  - name: airdrop
    coins:
      - 100000000utat

  - name: faucet
    coins:
      - 100000000utat

client:
  openapi:
    path: docs/static/openapi.json

faucet:
  name: faucet
  coins:
    - 100000utat

validators:
  - name: validator
    bonded: 100000000utat
