version: 1
validation: sovereign
default_denom: utat
genesis:
  chain_id: tat-1
build:
  binary: tatcoind

accounts:
- name: alice
  coins:
  - 200000000utat

- name: bob
  coins:
  - 100000000utat

client:
  openapi:
    path: docs/static/openapi.json

faucet:
  name: bob
  coins:
  - 100000utat

validators:
- name: alice
  bonded: 100000000utat

- name: validator1
  bonded: 200000000utat

- name: validator2
  bonded: 100000000utat
